version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    container_name: ${PROJECT_NAME}-gateway
    volumes:
      - ./gateway:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
