"""Add: OTPVerification

Revision ID: 0fa372f30532
Revises:
Create Date: 2025-04-30 01:47:16.142391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fa372f30532"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "otp_verification", sa.Column("is_verified", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "otp_verification", sa.Column("expires_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("otp_verification", "expires_at")
    op.drop_column("otp_verification", "is_verified")
    # ### end Alembic commands ###
