"""Update: OTPVerification

Revision ID: f7a04092c8b3
Revises: 7a1f85f5de07
Create Date: 2025-05-08 22:30:33.525440

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7a04092c8b3"
down_revision: Union[str, None] = "7a1f85f5de07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("otp_verification", sa.Column("is_used", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("otp_verification", "is_used")
    # ### end Alembic commands ###
