"""Update user model

Revision ID: 2b4e73f83e57
Revises: 6eda6645f042
Create Date: 2025-07-04 15:40:48.848048

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b4e73f83e57"
down_revision: Union[str, Sequence[str], None] = "6eda6645f042"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("age", sa.Integer(), nullable=True))
    op.add_column(
        "users", sa.Column("profession", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profession")
    op.drop_column("users", "age")
    # ### end Alembic commands ###
